version: '3.8'

services:
  app1:
    build: ./consumer-api
    container_name: api-server-1
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/concert_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  app2:
      build: ./consumer-api
      container_name: api-server-2
      ports:
        - "8082:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/concert_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
  mysql:
    image: mysql:8.0
    container_name: concert-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: concert_db
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci