version: '3.8'

services:
  gateway:
    build: ./api-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - app1
      - app2
  app1:
    build: ./consumer-api
    container_name: api-server-1
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/concert_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=75.0
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  app2:
      build: ./consumer-api
      container_name: api-server-2
      ports:
        - "8082:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/concert_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
        JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=75.0
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 512M
  mysql:
    image: mysql:8.0
    container_name: concert-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: concert_db
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:8.6.0
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  master:
    image: locustio/locust
    container_name: locust-master
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/rate_limit_test.py --master
  worker1:
    image: locustio/locust
    container_name: locust-worker-1
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/rate_limit_test.py --worker --master-host master
